export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREV_QUESTION = 'PREV_QUESTION';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const RESET_RESULTS = 'RESET_RESULTS';
export const RESET_INDEX = 'RESET_INDEX';
export const SET_ANSWER = 'SET_ANSWER';
